[workspace]
authors = ["Nick Miller <nicklamiller@gmail.com>"]
channels = ["conda-forge"]
name = "basic-c"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
clang = "17.*"
clang-format = ">=21.1.0,<22"
